apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: image
global:
  registry: LOCAL_REGISTRY

charts:
- name: istio-operator
  override:
    hub: $(registry)/istio-testing
    tag: latest

- name: servicemesh-controlplane
  override: 
    IstioOperator.image.hub: $(registry)/istio-testing
    IstioOperator.image.tag: 1.14-alpha.82cbd49db92acce69184ab4e9b95e033ea8ab390

- name: servicemesh-gateway
  override:
    IstioOperator.image.hub: $(registry)/istio-testing
    IstioOperator.image.tag: 1.14-alpha.82cbd49db92acce69184ab4e9b95e033ea8ab390

- name: jaeger-operator
  override:
    image.repository: $(registry)/jaegertracing/jaeger-operator
    image.tag: 1.24.0
    collectorImage.repository: $(registry)/jaegertracing/jaeger-collector
    collectorImage.tag: 1.24.0
    agentImage.repository: $(registry)/jaegertracing/jaeger-agent
    agentImage.tag: 1.24.0
    ingesterImage.repository: $(registry)/jaegertracing/jaeger-ingester
    ingesterImage.tag: 1.24.0
    queryImage.repository: $(registry)/jaegertracing/jaeger-collector
    queryImage.tag: 1.24.0

- name: servicemesh-jaeger-resource
  override:
    image.repository: $(registry)/jaegertracing/jaeger-operator
    image.tag: 1.24.0
    collectorImage.repository: $(registry)/jaegertracing/jaeger-collector
    collectorImage.tag: 1.24.0
    agentImage.repository: $(registry)/jaegertracing/jaeger-agent
    agentImage.tag: 1.24.0
    ingesterImage.repository: $(registry)/jaegertracing/jaeger-ingester
    ingesterImage.tag: 1.24.0
    queryImage.repository: $(registry)/jaegertracing/jaeger-collector
    queryImage.tag: 1.24.0

- name: kiali-operator
  override:
    image.repo: $(registry)/kiali/kiali-operator
    image.tag: v1.38.1


