apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mariadb
spec:
  values:
    volume:
      enabled: true
      use_local_path_for_single_pod_cluster:
        enabled: false
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: glance
spec:
  values:
    storage: rbd
    conf:
      ceph:
        enabled: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nova
spec:
  values:
    conf:
      ceph:
        enalbed: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: libvirt
spec:
  values:
    conf:
      ceph:
        enalbed: true
