apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: openvswitch
  labels:
    name: openvswitch
spec:
  releaseName: openvswitch
  targetNamespace: openstack
  wait: true
  chart:
    git: https://github.com/openinfradev/openstack-helm-infra.git
    ref: taco-v20.05
    path: openvswitch
  values:
    release_group: null
    images:
      tags:
        openvswitch_db_server: $(Values.site.spec.docker_registry)/$(Values.site.spec.openstack_version)/ubuntu-source-openvswitch-db-server:taco-0.1.0
        openvswitch_vswitchd: $(Values.site.spec.docker_registry)/$(Values.site.spec.openstack_version)/ubuntu-source-openvswitch-vswitchd:taco-0.1.0
        dep_check: $(Values.site.spec.docker_registry)/airshipit/kubernetes-entrypoint:v1.0.0
        image_repo_sync: $(Values.site.spec.docker_registry)/docker:17.07.0
      pull_policy: IfNotPresent
    pod:
      security_context:
        openvswitch_db_server:
          pod:
            runAsUser: 0
          container:
            server:
              runAsUser: 0
      user:
        nova:
          uid: 42436
