apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: image
global:
  registry: private-registry:5000

charts:
- name: elasticsearch-kibana
  override:
    customResource.elasticsearch.image.repository: $(registry)/elasticsearch/elasticsearch
    customResource.elasticsearch.image.tag: 7.5.1
    customResource.kibana.image.repository: $(registry)/kibana/kibana
    customResource.kibana.image.tag: 7.5.1

- name: elasticsearch-operator
  override:
    elasticsearchOperator.hyperkubeImage.repository: $(registry)/hyperkube
    elasticsearchOperator.hyperkubeImage.tag: v1.17.6
    elasticsearchOperator.image.repository: $(registry)/eck/eck-operator
    elasticsearchOperator.image.tag: 1.1.1

- name: fed-addons
  override:
    kibanaInit.image.repository: $(registry)/kibana-init
    kibanaInit.image.tag: v4
    metricbeat.image.repository: $(registry)/metricbeat
    metricbeat.image.tag: taco-1.0.0
    tacoWatcher.joinCluster.image.repository: $(registry)/curl
    tacoWatcher.joinCluster.image.tag: latest

- name: fluentbit
  override:
    image.exporter.repository: $(registry)/logalert-exporter
    image.exporter.tag: v0.1.1
    image.fluentbit.repository: $(registry)/fluent-bit-for-operator
    image.fluentbit.tag: v1.4.6
    image.hyperkube.repository: $(registry)/hyperkube
    image.hyperkube.tag: v1.17.6
    image.init.repository: $(registry)/library/docker
    image.init.tag: 19.03
    image.operator.repository: $(registry)/fluentbit-operator
    image.operator.tag: v0.2.0

- name: fluentbit-operator
  override:
    image.exporter.repository: $(registry)/logalert-exporter
    image.exporter.tag: v0.1.1
    image.fluentbit.repository: $(registry)/fluent-bit-for-operator
    image.fluentbit.tag: v1.4.6
    image.hyperkube.repository: $(registry)/hyperkube
    image.hyperkube.tag: v1.17.6
    image.init.repository: $(registry)/library/docker
    image.init.tag: 19.03
    image.operator.repository: $(registry)/fluentbit-operator
    image.operator.tag: v0.2.0

- name: grafana
  override:
    downloadDashboardsImage.repository: $(registry)/curl
    downloadDashboardsImage.tag: 7.68.0
    image.repository: $(registry)/grafana
    image.tag: 6.6.2
    initChownData.image.repository: $(registry)/library/busybox
    initChownData.image.tag: 1.31.1
    sidecar.image: $(registry)/k8s-sidecar:0.1.99
    testFramework.image: $(registry)/bats
    testFramework.tag: v1.1.0

- name: kube-state-metrics
  override:
    image.repository: $(registry)/coreos/kube-state-metrics
    image.tag: v1.9.5

- name: prometheus
  override:
    prometheus.prometheusSpec.image.repository: $(registry)/prometheus/prometheus
    prometheus.prometheusSpec.image.tag: v2.15.2

- name: prometheus-adapter
  override:
    image.repository: $(registry)/k8s-prometheus-adapter-amd64
    image.tag: v0.6.0

- name: prometheus-fed-master
  override:
    alertmanager.alertmanagerSpec.image.repository: $(registry)/prometheus/alertmanager
    alertmanager.alertmanagerSpec.image.tag: v0.20.0
    prometheus.prometheusSpec.image.repository: $(registry)/prometheus/prometheus
    prometheus.prometheusSpec.image.tag: v2.15.2

- name: prometheus-node-exporter
  override:
    image.repository: $(registry)/prometheus/node-exporter
    image.tag: v0.18.1

- name: prometheus-operator
  override:
    prometheusOperator.admissionWebhooks.patch.image.repository: $(registry)/kube-webhook-certgen
    prometheusOperator.admissionWebhooks.patch.image.tag: v1.0.0
    prometheusOperator.configmapReloadImage.repository: $(registry)/coreos/configmap-reload
    prometheusOperator.configmapReloadImage.tag: v0.0.1
    prometheusOperator.hyperkubeImage.repository: $(registry)/hyperkube
    prometheusOperator.hyperkubeImage.tag: v1.17.6
    prometheusOperator.image.repository: $(registry)/coreos/prometheus-operator
    prometheusOperator.image.tag: v0.37.0
    prometheusOperator.prometheusConfigReloaderImage.repository: $(registry)/coreos/prometheus-config-reloader
    prometheusOperator.prometheusConfigReloaderImage.tag: v0.37.0
    prometheusOperator.tlsProxy.image.repository: $(registry)/ghostunnel
    prometheusOperator.tlsProxy.image.tag: v1.5.2

- name: prometheus-process-exporter
  override:
    images.tags.dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
    images.tags.image_repo_sync: $(registry)/library/docker:17.07.0
    images.tags.process_exporter: $(registry)/process-exporter:0.2.11

- name: prometheus-pushgateway
  override:
    image.repository: $(registry)/pushgateway
    image.tag: v1.2.0

- name: kubernetes-event-exporter
  override:
    image.repository: $(registry)/siim/kubernetes-event-exporter
    image.tag: 0.1.0
    image.PullPolicy: IfNotPresent