---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: neutron
spec:
  values:
    conf:
      neutron:
        DEFAULT:
          l3_ha: false
          service_plugins: ""
      plugins:
        ml2_conf:
          ml2:
            mechanism_drivers: $(Values.site.spec.network.network_backend)
            type_drivers: flat, vlan
            tenant_network_types: ""
          ml2_type_flat:
            flat_networks: "*"
          ml2_type_vlan:
            network_vlan_ranges: provider
        openvswitch_agent:
          ovs:
            bridge_mappings: $(Values.site.spec.network.interface_mappings)
        linuxbridge_agent:
          linux_bridge:
            physical_interface_mappings: ""
            bridge_mappings: ""
    network:
      backend:
      - $(Values.site.spec.network.network_backend)
      share_namespaces: true
      auto_bridge_add:
        br-ex: $(Values.site.spec.network.auto_bridge_add_interface)
    manifests:
      daemonset_lb_agent: false
      daemonset_dhcp_agent: true
      daemonset_metadata_agent: false
      daemonset_ovs_agent: true
      daemonset_sriov_agent: false
      daemonset_l3_agent: false
