apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

charts:
- name: jaeger-operator
  override:
    jaeger.spec.storage.options.es:
      server-urls: https://eck-elasticsearch-es-http:9200
      username: elastic
      password: tacoword

- name: service-mesh-resource
  override:
    IstioOperator.meshConfig.sampling: 100
    IstioOperator.ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        namespace: istio-namespace1
        k8s:
          resources:
            requests:
              cpu: 500m # default 500m
              memory: 1024Mi # default 2048Mi
            limits:
              cpu: 1000m # default 500m
              memory: 2048Mi # default 2048Mi
          hpaSpec:
            maxReplicas: 10 # default 5
            minReplicas: 2 # defulat 1
    IstioOperator.egressGateways:
      - name: istio-egressgateway
        enabled: true
        namespace: istio-namespace1
        k8s:
          resources:
            requests:
              cpu: 500m # default 500m
              memory: 1024Mi # default 2048Mi
            limits:
              cpu: 1000m # default 500m
              memory: 2048Mi # default 2048Mi
          hpaSpec:
            maxReplicas: 10 # default 5
            minReplicas: 2 # defulat 1