apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  clusterName: cluster.local
  storageClassName: ceph
  repository: http://master-1:8879
  keycloakDomain: keycloak.example.com
  keycloakPassword: password
charts:
- name: keycloak
  source:
    repository: $(repository)
  override:
    clusterDomain: $(clusterName)
    global.storageClass: $(storageClassName)
    keycloak:
      ingress:
        hosts:
          - $(keycloakDomain)
        tls:
          - hosts:
            - $(keycloakDomain)
            secretName: tls-keycloak
      password: $(keycloakPassword)
    postgresql:
      postgresqlUsername: keycloak
      postgresqlPassword: $(keycloakPassword)
      postgresqlDatabase: keycloak
      postgresqlPostgresPassword: $(keycloakPassword)
      persistence:
        enabled: true
      metrics:
        enabled: true
- name: cloud-console
  source:
    repository: $(repository)
  override:
    ingress.enabled: false
    volume.storageClassName: $(storageClassName)
    config.service.proxyurl.format: "http://proxy-%REQUEST_PORT%.sktelecom.com"
    config.keycloak.url: "https://keycloak.sktelecom.com/auth"
    config.keycloak.realm: nextpaas
    config.keycloak.cacert: TO_BE_FIXED
    config.lenz.url: "http://dashboard.sktelecom.com"
- name: custom-network
  source:
    repository: $(repository)
  override:
    f5_ingress.enabled: false
    f5_ingress.ingresses: TO_BE_FIXED
    service.enabled: false
    service.endpoints: TO_BE_FIXED
- name: taco-registry
  source:
    repository: $(repository)
  override:
    storageClassName: $(storageClassName)
    tacoRegistry.volume.data.size: 10Gi
    tacoDb.volume.storageClassName: $(storageClassName)
    tacoClair.deployment.hostAliases: TO_BE_FIXED 
    tacoRegistryBuilder.deployment.hostAliases: TO_BE_FIXED 
    tacoRegistryBuilder.mirrors: TO_BE_FIXED
    tacoRegistryApp.deployment.env: TO_BE_FIXED 
- name: site-mirror-registry
  source:
    repository: $(repository)
  override:
    tacoRegistry.volume:
      storageClassName: $(storageClassName)
      data:
        size: 500Gi
- name: cronjob-backup-cloudconsole
  source:
    repository: $(repository)
  override:
    configmap.cloudconsoleUrl: TO_BE_FIXED
    configmap.backup.servers:
    - TO_BE_FIXED
    secret.password: TO_BE_FIXED
- name: cronjob-backup-keycloak
  source:
    repository: $(repository)
  override:
    configmap.backup.servers:
    - TO_BE_FIXED
    secret.password: TO_BE_FIXED
